site_name: Smallrye Mutiny Zero
repo_url: https://github.com/smallrye/smallrye-mutiny-zero
edit_uri: edit/main/docs/

nav:
  - Overview: 'index.md'
  - Quick start: 'quick-start.md'
  - Javadoc: './apidocs/index.html'

copyright: >-
  Sponsored by <a href="https://www.redhat.com"><img style="vertical-align: middle; height: 2.5em;" alt="Red Hat" src="./assets/redhat_reversed.svg"/></a> <br/>
  <a href="https://creativecommons.org/licenses/by/3.0/">CC by 3.0</a> |
  <a href="https://www.redhat.com/en/about/privacy-policy">Privacy Policy</a>

theme:
  name: material
  palette:
    primary: white
    accent: red
  font:
  features:
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition

extra:
  manifest: manifest.webmanifest
  version:
    provider: mike
